import { ACTIVE_STATE, INACTIVE_STATE, ERROR_STATE } from './states'
import { DEVICE_LIST_PAGE_KEY, HOLDING_LIST_PAGE_KEY } from './pages'
import { PROVIDER_LIST_PAGE_KEY } from './pages'

const STATE_COLORS = {
  [ACTIVE_STATE]: 'success',
  [INACTIVE_STATE]: 'danger',
  [ERROR_STATE]: 'warning'
}

const DEFAULT_ELEMENT_QUANTITY = 5
const OPTION_ELEMENT_QUANTITY = [10, 50, 100, 150, 200]
const INVALID_ELEMENT_QUANTITY = ['']

const ACTIONS_KEY = 'actions'

const ENTITIES_ID = {
  [HOLDING_LIST_PAGE_KEY]: 'holdingId',
  [DEVICE_LIST_PAGE_KEY]: 'deviceId',
  [PROVIDER_LIST_PAGE_KEY]: 'providerId'
}

const ACTION_ICON_KEY = {
  viewList: { icon: 'hiOutlineViewList', color: 'default' },
  modify: { icon: 'hiOutlinePencilAlt', color: 'yellow' }
}

const MILLISECOND_INDICATOR = 'ms'
const SECOND_INDICATOR = 's'
const MINUTE_INDICATOR = 'm'
const HOUR_INDICATOR = 'h'

const MILLISECOND_LIMIT = 1
const SECOND_LIMIT = 60
const MINUTE_LIMIT = 3600

const SERVICE_TYPE_KEY = 'serviceType'
const SERVICE_STATE_KEY = 'serviceState'

export {
  STATE_COLORS,
  DEFAULT_ELEMENT_QUANTITY,
  OPTION_ELEMENT_QUANTITY,
  INVALID_ELEMENT_QUANTITY,
  ACTIONS_KEY,
  ENTITIES_ID,
  ACTION_ICON_KEY,
  MILLISECOND_INDICATOR,
  SECOND_INDICATOR,
  MINUTE_INDICATOR,
  HOUR_INDICATOR,
  MILLISECOND_LIMIT,
  SECOND_LIMIT,
  MINUTE_LIMIT,
  SERVICE_TYPE_KEY,
  SERVICE_STATE_KEY
}
