const DASHBOARD_PAGE_KEY = 'dashboardPage'
const HOLDING_LIST_PAGE_KEY = 'holdingListPage'
const PROVIDER_LIST_PAGE_KEY = 'providerListPage'
const DEVICE_LIST_PAGE_KEY = 'deviceListPage'
const ADMIN_PAGE_KEY = 'adminPage'

const ALL_PAGES = [
  DASHBOARD_PAGE_KEY,
  HOLDING_LIST_PAGE_KEY,
  PROVIDER_LIST_PAGE_KEY,
  DEVICE_LIST_PAGE_KEY,
  ADMIN_PAGE_KEY
]

export {
  DASHBOARD_PAGE_KEY,
  HOLDING_LIST_PAGE_KEY,
  PROVIDER_LIST_PAGE_KEY,
  DEVICE_LIST_PAGE_KEY,
  ADMIN_PAGE_KEY,
  ALL_PAGES
}
