const SERVER = import.meta.env.VITE_SERVER
const PROVIDER_PATH = import.meta.env.VITE_PROVIDER_PATH
const HOLDING_PATH = import.meta.env.VITE_HOLDING_PATH
const AUTH_PATH = import.meta.env.VITE_AUTH_PATH

const NO_PATH = ''
const DASHBOARD_PAGE_PATH = '/'
const ADMIN_PAGE_PATH = '/admin'
const HOLDING_LIST_PAGE_PATH = `${ADMIN_PAGE_PATH}/holding-list`
const PROVIDER_LIST_PAGE_PATH = `${HOLDING_LIST_PAGE_PATH}/provider-list/:holdingId`
const PROVIDER_MODIFY_PAGE_PATH = `${PROVIDER_LIST_PAGE_PATH}/provider-modify/:providerId`
const DEVICE_LIST_PAGE_PATH = `${ADMIN_PAGE_PATH}/device-list`

export {
  SERVER,
  PROVIDER_PATH,
  HOLDING_PATH,
  DASHBOARD_PAGE_PATH,
  ADMIN_PAGE_PATH,
  HOLDING_LIST_PAGE_PATH,
  PROVIDER_LIST_PAGE_PATH,
  PROVIDER_MODIFY_PAGE_PATH,
  DEVICE_LIST_PAGE_PATH,
  NO_PATH,
  AUTH_PATH
}
