const EMISSION_KEY = 'issuance'
const CONCILIATION_KEY = 'conciliation'
const CERTIFICATION_KEY = 'certification'
const FOLIO_REQUEST_KEY = 'folioRequest'
const VALORIZATION_KEY = 'valorization'
const ANNULMENT_KEY = 'annulment'

const SERVICES_KEY = [
  EMISSION_KEY,
  CONCILIATION_KEY,
  CERTIFICATION_KEY,
  FOLIO_REQUEST_KEY,
  VALORIZATION_KEY,
  ANNULMENT_KEY
]

export {
  EMISSION_KEY,
  CONCILIATION_KEY,
  CERTIFICATION_KEY,
  FOLIO_REQUEST_KEY,
  VALORIZATION_KEY,
  ANNULMENT_KEY,
  SERVICES_KEY
}
