const ACTIVE_STATE = 1
const INACTIVE_STATE = 0

const AVAILABLE_STATE = 1
const ERROR_STATE = 2
const UNAVAILABLE_STATE = 0

const FEMALE_STATE = 'F'
const MALE_STATE = 'M'

const EXCEPTION_STATUS = 0
const SUCCESS_STATUS = 1
const ERROR_STATUS = 2
const UNAUTHORIZED_STATUS = 4

export {
  ACTIVE_STATE,
  INACTIVE_STATE,
  AVAILABLE_STATE,
  UNAVAILABLE_STATE,
  FEMALE_STATE,
  MALE_STATE,
  ERROR_STATE,
  EXCEPTION_STATUS,
  SUCCESS_STATUS,
  ERROR_STATUS,
  UNAUTHORIZED_STATUS
}
